# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5b52c17e3b2da57b61efd161052f59e"
application_url = "https://rtg-roomie-chatbot.vercel.app"
embedded = true
name = "rtgtheme"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://rtg-roomie-chatbot.vercel.app/api/shopify/webhooks/app-uninstalled"

[auth]
redirect_urls = [ "https://rtg-roomie-chatbot.vercel.app/api/shopify/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
