/**
 * Prebuild: converts Excel catalog, SYSTEM_PROMPT.md, and skills/*.md into
 * importable .ts data files under src/data/. These are then bundled normally
 * by Turbopack/webpack — no runtime filesystem reads on Vercel.
 *
 * Run via: node scripts/prebuild.js
 * Called automatically before "next build" in the npm build script.
 */
const { readFileSync, writeFileSync, mkdirSync, readdirSync } = require("fs");
const { join, basename } = require("path");
const XLSX = require("xlsx");

const OUT = "src/data";
mkdirSync(OUT, { recursive: true });

// ── 1. Excel catalog → JSON rows + raw markdown text ──
const wb = XLSX.read(readFileSync("updated rtg.xlsx"), { type: "buffer" });
const rows = XLSX.utils.sheet_to_json(wb.Sheets["Upload sheet"], {
  defval: "",
  raw: false,
});
const headers = Object.keys(rows[0] || {});
const headerLine = headers.join(" | ");
const separator = headers.map(() => "---").join(" | ");
const dataLines = rows.map((row) =>
  headers.map((h) => String(row[h] ?? "").trim()).join(" | ")
);
const rawText = [headerLine, separator, ...dataLines].join("\n");

writeFileSync(
  join(OUT, "catalog-raw.ts"),
  `// AUTO-GENERATED by scripts/prebuild.js — do not edit\nexport const CATALOG_RAW = ${JSON.stringify(rawText)};\nexport const CATALOG_ROWS: Record<string, string>[] = ${JSON.stringify(rows)};\n`
);
console.log(`✓ catalog-raw.ts — ${rows.length} rows, ${rawText.length} chars`);

// ── 2. SYSTEM_PROMPT.md → string export ──
const systemPrompt = readFileSync("SYSTEM_PROMPT.md", "utf-8");
writeFileSync(
  join(OUT, "system-prompt-raw.ts"),
  `// AUTO-GENERATED by scripts/prebuild.js — do not edit\nexport const SYSTEM_PROMPT_RAW = ${JSON.stringify(systemPrompt)};\n`
);
console.log(`✓ system-prompt-raw.ts — ${systemPrompt.length} chars`);

// ── 3. skills/*.md → key-value map export ──
const skillsDir = "skills";
const skills = {};
for (const f of readdirSync(skillsDir)) {
  if (!f.endsWith(".md")) continue;
  const name = basename(f, ".md");
  skills[name] = readFileSync(join(skillsDir, f), "utf-8");
}
writeFileSync(
  join(OUT, "skills-raw.ts"),
  `// AUTO-GENERATED by scripts/prebuild.js — do not edit\nexport const SKILLS: Record<string, string> = ${JSON.stringify(skills)};\n`
);
console.log(
  `✓ skills-raw.ts — ${Object.keys(skills).length} skills: ${Object.keys(skills).join(", ")}`
);

console.log("\nPrebuild complete.");
